### ISSUE TITLE
Speed of loaded page slower then normal .htaccess  solution

### ISSUE THREAD

**Issue by gundestrup** [litespeedtech/lscache-joomla#2]
Loadtime "pingdom speedtest" 650-627ms vs 350-299ms
 (even on multiable reload).
`
#<IfModule LiteSpeed>
#	CacheEnable public
#    RewriteEngine On
#    RewriteCond %{REQUEST_METHOD} ^HEAD|GET$
#    RewriteCond %{HTTP_HOST} ^lungekursus.dk|a2.lungekursus.dk|www.lungekursus.dk [NC]
#    RewriteCond %{HTTP_COOKIE} !loginuser
#    RewriteCond %{ORG_REQ_URI} !^/index.php$
#    RewriteCond %{ORG_REQ_URI} !administrator
#    RewriteCond %{ORG_REQ_URI} (\.php|\.html|\.htm|\.feed|\.pdf|\.raw|/[^.]*)$  [NC]
#    RewriteCond %{QUERY_STRING} !nocache
#    RewriteCond %{REQUEST_URI} !^/[0-9]+\..+\.cpaneldcv$
#    RewriteCond %{REQUEST_URI} !^/\.well-known/acme-challenge/[0-9a-zA-Z_-]+$
#    RewriteCond %{REQUEST_URI} !^/\.well-known/pki-validation/[A-F0-9]{32}\.txt(?:\ Comodo\ DCV)?$
#    RewriteRule .* - [E=Cache-Control:max-age=1]
#</IfModule>
##plugin Litespeed code
<IfModule LiteSpeed>
CacheLookup on
RewriteEngine On
RewriteRule .* - [E=esi_on:1]
</IfModule>
`

**Comment by gundestrup** [comment]
very stange, reenabled the code you provide, now load time is 299ms? (pingdom speedtest - test server sweden) (jotcache cleared, litespeed cache clered, joomla cache cleared).
Next test: load time is 4200ms, (pingdom speedtest - test server sweden).
Next test: 800ms

**Comment by jacksonlst** [comment]
What do you means: "reenabled the code you provide" ? Do you means to use joomla cache plugin?

Cache TTL seems too short:

  RewriteRule .* - [E=Cache-Control:max-age=1]

your rewrite rule only cache file for 1 second, you should change it to something longer, otherwise it may not be served from cache.

  RewriteRule .* - [E=Cache-Control:max-age=120]

**Comment by gundestrup** [comment]
I changed the age to 360, same problem.
Regarding the code
The first setup is LScaching via .htaccess, code via a2hosting.
When I disable that code and enable the .htaccess you provide to user the code via the github plugin, thi i the result. (very unstable load times).

**Comment by jimhill10** [comment]
I just copied my production site over to my staging server.  Configured the beta Litespeed plugin, removed the old htacess directives and added the new one per the instructions.  Before I bother running any speed tests I first inspected the page header.  I see that the Litespeed server is reporting x-litespeed-cache with a value of "miss."  That is a red flag as with the htacess directive on production I expect to see and so see "hit."  Did you look at your page header for the site with the new cache plugin?  

Question, does anyone know which server directory the cache files are being stored?  My staging server is on the same one as production and I am hoping the files are not being sent to the usual "lscache" which would mix with production.

**Comment by jacksonlst** [comment]
Yes. The first visit will be "miss", then you should see "hit" at the second visit. You should look for "X-LiteSpeed-Cache: hit" to ensure the cache is actually working before you run any test.

**Comment by jacksonlst** [comment]
Also don't miss the rewrite rules based cache enabling method with plugin-based cache enabling method.
and disable other joomla full page cache plugin first before enabling LiteSpeed cache plugin.

The cache files are stored as files on disk and cache root will be set at LSWS or apache conf. 
https://www.litespeedtech.com/support/wiki/doku.php/litespeed_wiki:cache#prerequisites 
Configure Cache Root section.

**Comment by jacksonlst** [comment]
for performance issue reported, mainly due to some setup issue. We have obtained the login for the server.  After we fixed the configuration issue, we will show the test figure here. We will also run some benchmark tests and show you the result.

**Comment by jimhill10** [comment]
I have a testing site using the Litespeed plugin which in every other way replicates production which uses htaccess directives for Litespeed cache.    Both sites use JCH Optimize with a CDN.  I am having an issue with a long first byte time on the test site.  It is a full 2 seconds longer than production.  Other than that the page load time is similar.    See this test:
[Bytcheck testing site](http://www.bytecheck.com/results?resource=https%3A%2F%2Fwww.staging.ufcinc.com%2FData-Capture-and-OCR%2Fabbyy-flexicapture-document-capture-software)
[Bytecheck production](http://www.bytecheck.com/results?resource=https%3A%2F%2Fwww.ufcinc.com%2FData-Capture-and-OCR%2Fabbyy-flexicapture-document-capture-software)

Second, can you clarify what other cache/compression directives you are using?   We have a variety of directives in our production site.  I took them out of the test site in order to try to solve the long TTFB.  Here are the ones in place on production:

- mod_gzip directives. 
- mod_deflate directives (AddOutputFilterByType DEFLATE text/html, etc. added by JCH Optimize) 
- Etag Optimization directives. Expires ByType ...(added by JCH Optimize)

**Comment by gundestrup** [comment]
There is still no solution
they have currently done the following:
> We also disabled some conflict plugins in joomla administrator panel, we
> disabled "Recache" plugin, dsabled "JotCache" plugin, disabled "System -
> Page Cache" plugin, disabled "System - Regular Labs - Cache Cleaner" plugin

I have copyed my production server, and given them full access, but I cannot report any progress.
Last login from the firm was 24h ago, form spain and USA...

So I guess it's more difficult then a simple fix.

When I know more, I or the firm will update

**Comment by jimhill10** [comment]
I am trying to track down what is causing my long TTFB on my dev site while production is almost zero.  I will spend some time on this to disable every plugin as well as use the Joomla debug to analyze queries and see what is taking so long.

**Comment by jimhill10** [comment]
I have 1.0.1 running in production and I think that this is actually faster than the former htacess directive method.  I am interested if others are seeing the same thing. I am using a few values to match a regex in the exclusions list, and a bunch of modules in ESI mode including all the Rsforms.  So I am not seeing a repeat of what I saw on our dev site with this issue.

**Comment by gundestrup** [comment]
Closing, after upgradring to 1.20 of plugin, and duing my speed testing it's no longer a problem. 
I suggest upgrading to newest version of plugin
