### ISSUE TITLE
Conflict with minifying plugins

### ISSUE THREAD

**Issue by omikron** [litespeedtech/lscache-joomla#20]
I have noticed a conflict on Joomla sites running some kind of CSS/JS minifying plugin. If the minifying plugin changes a CSS/JS URL the link is broke until the cache is regenerated.

Is there any way to avoid this?

**Comment by WuhuaChen** [comment]
Can you give me the name of the minifying plugin, I may need to test it.  Normally, if the plugin works automatically in background, it should not matter. LSCache will only cache the content output to browser, so the content should already been minified.

If you manually minify some specific web pages via a GUI button,  and changed some php file souce code,  you need to manually purge all litespeed cache as well.

**Comment by omikron** [comment]
The plugin is [JCH Optimize](https://www.jch-optimize.net). I am using the PRO version, but I am not sure if the issue is specific to PRO.

The plugin creates cache files containing the minified CSS and JS, but I am not sure how the files are being removed causing the 404 errors. I am not able to replicate it - it happens hours to days after the cache is cleared depending on the website. I think it could be related to [this](https://www.jch-optimize.net/documentation/manage-cache.html).

**Comment by jimhill10** [comment]
I am having this same issue.  For me what happens is that I see broken CSS and javascript on pages. Using the Chome console I then see a variety of 404 errors for missing javascript and css files in the path /media/plg_jchoptimize/cache/<long alphanumeric string>_0.css 

When I look inside of SH404SEF I then see 404 errors produced in the internal category.   On the Chrome console for the broken page it shows a similar URL but since we use a CDN it is the CDN URL.

I have been trying to solve this for several days but it keeps coming back.  For now really all I can do is to disable JCH Optimize Pro until I can get it figured out.

**Comment by WuhuaChen** [comment]
I agree with @omikron ，[This article](https://www.jch-optimize.net/documentation/manage-cache.html) shows that jch_optimize will generate js/css file and share these js/css file across different php pages.  but jch_optimize also have a combine feature allow small js/css to be combined together.  So I guess some shared js/css file have been combined and removed cause some relate cached php web page 404 issue.  If manually purged these page's cache, and generate cache again, it will be minify again so problem will gone.  
I think, if we have two php web page with exact same content,  it should share some js/css file, visit both web page,  then enable the combine featue,   visit one web page again, to see if those shared js/css file was removed/combined or not.

**Comment by WuhuaChen** [comment]
@omikron I setup a testing environment have both LiteSpeed Cache and JCH_Optimize enabled, it works fine together.  I'm sure LiteSpeed Cache plugin will not delete any css/js file generated by JCH_Optimize.  [This article](https://www.jch-optimize.net/support/94-documentation/faq.html) said it might be url rewriting or file permission problem, I'm not sure. Because Litespeed cache on Wordpress has its own html optimze and CDN feature, it will change the output content before it reach browser. but Litespeed cache in joomla will not change output content or js/css file at all.

**Comment by gundestrup** [comment]
I can confirm that using JCH optimizer is working perfectly.
I did use CDN, but deselected to use it because of speed of litespeed, and the additional time the SSL handshake took, slowed down my website...
But if the caching time setting is not long for both components (Joomla - global setting, and litespeed caching), and you dont't have a proper cache clearning plugin, you get in to trubble.

**Comment by omikron** [comment]
I talked to the developer of JCH for their opinion and they said;

> Are you using Google fonts on these sites? The plugin generates a different cache file(name) based on the type of browser that accesses the site to reflect the different font type that Google would load for that browser. This would explain why the file name didn't change when cache was deactivated but changed after cache was activated. The Cache plugin probably cached the page that was accessed by a different browser.
> 
> JCH Optimize cache is hard-coded to one day and will delete expired cache daily. So if a page was cached by LiteSpeed with a JCH Optimize file that had a few hours left on it, then after it becomes expired and somebody accesses another page that was not cached so allowing the plugin to run, this file gets deleted. When the cached page is accessed, then it breaks because the file that was cached in the page no longer exists.
> 
> In Joomla! recently we now clear the page cache whenever the Plugin deletes expired cache and I think that has helped with this issue in Joomla!. In WordPress there is no native cache API. I think we would need to delete anything under the /wp-content/cache/ folder to achieve the same effect here. I will try to implement this for the next version and see how that goes.
> 

I use google fonts on my sites having issues so I think this may be what my problem is. Anyone else using google fonts with JCH & LiteSpeed?

I think the changes they are talking about to JCH would not fix the issue with litespeed because of the way it work right?

**Comment by WuhuaChen** [comment]
"In Joomla! recently we now clear the page cache whenever the Plugin deletes expired cache and I think that has helped with this issue in Joomla!" ,  In LiteSpeed Cache plugin, in Options->Advanced  we have a web interface to purge all LiteSpeed Cache,  If you can persuade JCH to call this web interface when they clear joomla page cache, I think file missing problem will be solved. I emailed to them but I can't submit ticket so they didn't reply me.
About different browser generate different cache file name, we can add an option to generate different cache copy for different browser in later release, we can handle that.

**Comment by uglyeoin** [comment]
check this solution too possibly https://github.com/litespeedtech/lscache-joomla/issues/24#issuecomment-433629919
