### ISSUE TITLE
Joomla! duplicate key error when trying to create ESI modules

### ISSUE THREAD

**Issue by uglyeoin** [litespeedtech/lscache-joomla#28]
Whenever I try to generate ESI modules in the component I get an error dupicate key 279.  Had it on two sites now so pretty sure it's not a duplicate key, or if it is, then Joomla! has a duplicate key which is the same number each time.

**Comment by jimhill10** [comment]
I have used Akeeba Admin Tools since it came out and feel this is on my short list of required extensions for any Joomla site.  I especially appreciate the comprehensive htaccess builder with many comprehensive rules for blocking common exploits.  The duplicate key issue is something that others have reported and looks to be easy to fix. This article for example talks about it.  
[https://www.joomla-monster.com/blog/joomla-templates/solution-for-1602-duplicate-sql-entry-error-while-updating-to-joomla-3-6](url)

**Comment by uglyeoin** [comment]
I think I fixed this now and I'm pretty sure it's not plugin related so I'll close this.
