### ISSUE TITLE
Meta data is odd

### ISSUE THREAD

**Issue by uglyeoin** [litespeedtech/lscache-joomla#29]
My homepage meta data says

x^ﾍ 濤蔡9ﾍ賂9 "i 変ﾚ fl1 Y ｫ ﾒLЛﾊH$箔9 $｣ ﾀd4IHLｳ SQ2 *d樮ﾄ #ｵ "$\$？ ６~ ・ {\e謙陞泰 ﾒ8ｽ ｿﾂf/', -Bｮx 6 0rEc/汲 #ｿ$ｰ2堂 ｧjJﾉﾕ4共 ｡I@ﾔ盤H ...

Could this becaused by LiteSpeed Cache?

**Comment by wuhua68** [comment]
It may caused by gzip,  if not enabled LiteSpeed Cache it may happen some time but not every time. but with LiteSpeed Cache the error will be cached.
You can try disable gzip in Joomla admin panel->Global Configuration->Server->Gzip Page Compression, Then purge home page cache, by save relative menuitem, then refresh home page to see if problem solved.

**Comment by uglyeoin** [comment]
Interesting, it's not there in the source code like that.  I've taken your instructions all the same.  Perhaps I have to wait for Google to rescan.
